"""add_user_category_budgets_consolidate_budget_fields

Revision ID: 48778fbb0b0d
Revises: 0006_add_is_fixed_to_categories
Create Date: 2026-06-13 22:42:00.312266

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '48778fbb0b0d'
down_revision: str | None = '0006_add_is_fixed_to_categories'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('user_category_budgets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('budget_limit', sa.BigInteger(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id')
    )

    # Migrate existing per-user budget data from categories to user_category_budgets
    op.execute("""
        INSERT INTO user_category_budgets (id, user_id, category_id, budget_limit, is_fixed, created_at, updated_at)
        SELECT gen_random_uuid(), user_id, id, budget_limit, is_fixed, now(), now()
        FROM categories
        WHERE user_id IS NOT NULL AND (budget_limit IS NOT NULL OR is_fixed = true)
    """)

    op.drop_column('categories', 'budget_limit')
    op.drop_column('categories', 'is_fixed')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_fixed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('budget_limit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_table('user_category_budgets')
    # ### end Alembic commands ###
