"""add_account_initial_balance

Revision ID: 0011_add_account_initial_balance
Revises: 0010_add_savings_goals_table
Create Date: 2026-06-28 13:50:43.290855

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_add_account_initial_balance"
down_revision: str | None = "0010_add_savings_goals_table"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("initial_balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
    )
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False
    )
    op.drop_column("accounts", "initial_balance")
    # ### end Alembic commands ###
