"""add_chat_session_id_to_transactions

Revision ID: 0012_add_chat_session_id_to_transactions
Revises: 0011_add_account_initial_balance
Create Date: 2026-07-08 21:48:10.503397

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0012_add_chat_session_id_to_transactions'
down_revision: str | None = '0011_add_account_initial_balance'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('chat_session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'chat_session_id')
    # ### end Alembic commands ###
